### PR TITLE
Detail the minimum required version of node.js

### LINKED ISSUE #608: Which version of Node.js is needed to build eXide?
The `README.md` should say which version of Node.js is needed to build eXide.

I just tried with 12 - which generates warnings like:
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it
```

It then fails with this:
```
❯ npm run build

> exide@4.0.0 build /Users/aretter/code/eXide
> node scripts/build.js prepare && npm run xqlint && node scripts/build.js


> exide@4.0.0 xqlint /Users/aretter/code/eXide
> cd support/xqlint && node r.js -o build.js && cd ../..

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/Users/aretter/code/eXide/support/xqlint/r.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! exide@4.0.0 xqlint: `cd support/xqlint && node r.js -o build.js && cd ../..`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the exide@4.0.0 xqlint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aretter/.npm/_logs/2023-03-19T09_50_21_142Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! exide@4.0.0 build: `node scripts/build.js prepare && npm run xqlint && node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the exide@4.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aretter/.npm/_logs/2023-03-19T09_50_21_187Z-debug.log
```

I then also tried with 14 which fails with the error:
```
Run `npm audit` for details.
❯ npm run build

> exide@4.0.0 build
> node scripts/build.js prepare && npm run xqlint && node scripts/build.js


> exide@4.0.0 xqlint
> cd support/xqlint && node r.js -o build.js && cd ../..

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/Users/aretter/code/eXide/support/xqlint/r.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I also tried with 16,  which fails with a slightly different error:

```
❯ npm run build

> exide@4.0.0 build
> node scripts/build.js prepare && npm run xqlint && node scripts/build.js


> exide@4.0.0 xqlint
> cd support/xqlint && node r.js -o build.js && cd ../..

node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module '/Users/aretter/code/eXide/support/xqlint/r.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

----

So which version of Node.js is needed to build eXide, none of versions 12, 14, or 16 work for me :-(

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/eXide/issues/608

### CODE REVIEW

**Review by joewiz — APPROVED** [review]
LGTM, and good catch that ant is no longer part of the build process.

**Review by duncdrum — CHANGES_REQUESTED** [review]
So far we had a policy that the documentation and Ci config should be in sync when it comes to minimum versions. Please either bump the version in the readme or adjust CI so we also run tests against node12

**Comment by adamretter** [comment]
@duncdrum But... which version **should** we be using then?
I opened an issue about this 2 months ago here but no one answered the question - https://github.com/eXist-db/eXide/issues/608

**Comment by duncdrum** [comment]
@adamretter since 12 is long dead I would pick 14 as the officially supported min version, if not 16 as it has 2 more weeks of LTS left in it. Current LTS is 18

**Comment by adamretter** [comment]
@duncdrum Thanks. I have now updated the `README.md` to `14+`

**Review by duncdrum — APPROVED** [review]

**Pull request merged**
