### PR TITLE
[bugfix] outline view in sidebar

### PR DESCRIPTION
**Pull request by line-o**
The outline route returned statuscode 404 because it is in fact a post request and only get was allowed in the controller.

### CODE REVIEW

**Comment by line-o** [comment]
@dizzz here is the PR for the issue you reported yesterday.

**Review by dizzzz — APPROVED** [review]

**Review by joewiz — APPROVED** [review]
I can confirm the 404 in the current version and that the PR restores the feature. Thanks @line-o!

**Comment by joewiz** [comment]
I'd like to issue a new release based on this but noted a CI failure after merging the PR - see https://github.com/eXist-db/eXide/issues/651#issuecomment-2308956313. I haven't had time to dig into this to see if it's a real problem or a problem related to this PR. I'd be interested in others' opinions.

**Comment by line-o** [comment]
It is really just a flaky test that passes usually on the second run.

**Pull request merged**
