### PR TITLE
replace hipchat with slack

### PR DESCRIPTION
**Pull request by duncdrum**
see exist-db/exist#2475

### CODE REVIEW

**Review by joewiz — APPROVED** [review]

**Comment by joewiz** [comment]
It’s odd that this change would result in a CI failure.

**Comment by duncdrum** [comment]
nope `:latest` is broken, so is develop in the main repo, so forward looking tests are failing

**Comment by duncdrum** [comment]
hmm since this is a readme only change, i m a bit at a loss as to why the tests, keep getting stuck on latest. 

I have a theory that this might be due to when the PR was opened, in any case I would suggest to merge to get some fresh runs, if there are more problems i ll address them in a separate PR.

**Comment by joewiz** [comment]
Ok, let's try.

**Pull request merged**
