### PR TITLE
update CI config

### PR DESCRIPTION
**Pull request by marmoure**
update node version and only use exist latest as the release version have an old version of eXide that makes the current method of deployment fail

### CODE REVIEW

**Comment by marmoure** [comment]
@duncdrum here are the changes i introduced to the CI to make the tests run

**Comment by marmoure** [comment]
@joewiz  i moved the CI changes to this PR 
we are only testing the latest version to avoid the deploy conflict

**Comment by joewiz** [comment]
@marmoure Great! Is this ready for review, or are you still working on it?

**Comment by marmoure** [comment]
@joewiz this is ready for review

**Review by joewiz — APPROVED** [review]
CI checks pass and video artifacts are uploaded, showing successful run

**Comment by line-o** [comment]
Why is eXide not tested on the last released version of existdb anymore?

**Comment by marmoure** [comment]
@line-o there was an issue with deployment at the time 
we reintroduced the release version in another PR  
it's under review now

**Pull request merged**
